language: ruby
rvm:
 - 2.4.1
env:
 - DB=postgresql
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3
bundler_args: --binstubs=./bundler_stubs
