development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:19d469cd86bc30219fdd6fd1bc36e808@angelfish.redistogo.com:11426/
  channel_prefix: turing_professionals_production
